### ISSUE TITLE
Dataset Failed

### ISSUE THREAD

**Issue by pprikryl** [RENCI/fuse-dashboard-immcellfie#96]
Hello, could you please help me with that issue? I don't understand what's wrong. Thanks a lot.

![image](https://github.com/RENCI/fuse-dashboard-immcellfie/assets/33254369/569ed586-6dfd-4cde-9acf-4b5614ff8023)

**Comment by davidborland** [comment]
I noticed a couple of closed issues for this. Is it still a problem?

**Comment by pprikryl** [comment]
Yes, unfortunately, it is. I thought I would postpone it and try to solve it later. But I would be very grateful for the help.
I'm probably using your tool wrong. Can mass spectrometry data be used as input data? If so, can you guide me on how to transform the input data? Thanks.

**Comment by davidborland** [comment]
I don't think mass spectrometry data would work. It is designed to perform and visualize the results of metabolic task analysis of gene expression data. E.g. the first column of the input data should be an Entrez gene id.
